import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { ClientLayout } from "@/components/ClientLayout";
import { fetchData } from "@/libs/fetchData";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await fetchData();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-row justify-center">
          <div className="bg-home-bg-gradient bg-top absolute z-0 top-0 left-0" />
          <div className="relative h-screen w-full">
            <Header />
            <ClientLayout initialData={data}>{children}</ClientLayout>
            {/* <Footer /> */}
          </div>
        </div>
      </body>
    </html>
  );
}
